version: "3"
services:
  app:
    image: openjdk:8-jre
    working_dir: /usr/local/src
    entrypoint: bash
    volumes:
      - ./:/usr/local/src/
      - ${HOME}/.sbt:/root/.sbt
      - ${HOME}/.m2:/root/.m2
      - ${HOME}/.ivy2:/root/.ivy2