version: "3"
services:
  app:
    image: hseeberger/scala-sbt:8u171_2.12.6_1.1.6
    working_dir: /usr/local/src/helloworld
    entrypoint: bash                                                               
    volumes:
      - ./:/usr/local/src/
      - ${HOME}/.sbt:/root/.sbt
      - ${HOME}/.m2:/root/.m2
      - ${HOME}/.ivy2:/root/.ivy2